### ISSUE TITLE
Facing problem in admin login

### ISSUE THREAD

**Issue by nvy1207** [sudarakas/A-Zone#1]

**Comment by sudarakas** [comment]
@nvy1207 hi, can you explain the problem?

**Comment by nvy1207** [comment]
> @nvy1207 hi, can you explain the problem?

I am trying to add new admin but before that I need to login as admin. Can I get default login credentials?

**Comment by sudarakas** [comment]
> > @nvy1207 hi, can you explain the problem?
> 
> I am trying to add new admin but before that I need to login as admin. Can I get default login credentials?

**Admin Login**
username: admin@nanolabs.com
password: adminPass
